"""add prompt_definitions and prompt_few_shots

Revision ID: 1172963e5f16
Revises: e28f9684a92b
Create Date: 2026-01-07 11:55:56.362484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1172963e5f16'
down_revision: Union[str, Sequence[str], None] = 'e28f9684a92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('system_guardrails', sa.Text(), nullable=True),
    sa.Column('output_guideline', sa.Text(), nullable=True),
    sa.Column('output_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag', 'version', name='uq_prompt_tag_version')
    )
    op.create_table('prompt_few_shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['prompt_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_few_shots')
    op.drop_table('prompt_definitions')
    # ### end Alembic commands ###
