"""add prompt_definitions and prompt_few_shots

Revision ID: b2e330ceeb9b
Revises: ae71d42f1be2
Create Date: 2026-01-07 11:20:48.339862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e330ceeb9b'
down_revision: Union[str, Sequence[str], None] = 'ae71d42f1be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
