"""add prompt_definitions and prompt_few_shots

Revision ID: e28f9684a92b
Revises: b2e330ceeb9b
Create Date: 2026-01-07 11:23:47.667922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28f9684a92b'
down_revision: Union[str, Sequence[str], None] = 'b2e330ceeb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
